### ISSUE TITLE
Question : Qos Voip

### ISSUE THREAD

**Issue by Florent4223** [Ysurac/openmptcprouter#1067]
Hello

I have to pass on the VPN both data and voice (SIP protocol)
Can we prioritize the UDP protocol (IP voice support) over TCP?

thanks

version : 0.54.7 on RPI3

**Comment by Adorfer** [comment]
i did that manually by a) priorty for the AS of the SIP provider and b) by (the same) for the priority of the local SIP-phones IPs. 

An automatic rule for SIP-RTP would be nice (but since it uses lot's of ports, especially if you have dozends of SIP devices in a Network) 
![grafik](https://user-images.githubusercontent.com/10302493/84135031-bdb03e00-aa49-11ea-8e03-7b5b309c0db5.png)
![grafik](https://user-images.githubusercontent.com/10302493/84135122-d91b4900-aa49-11ea-9155-ac3d4b8cfae4.png)

**Comment by Florent4223** [comment]
it's great that's exactly what i need ... but where is the menu or do you set that?

**Comment by Florent4223** [comment]
sorry i just found
I will try it out thank you very much
