### ISSUE TITLE
Should i install nextdns to openmptcp router

### ISSUE THREAD

**Issue by rifaterdemsahin** [Ysurac/openmptcprouter#1100]
İf so Should I do command line install or just use the ips ?

**Comment by Ysurac** [comment]
You can add the IPs in Network->DHCP & DNS the same way as "127.0.0.1#5353" (it redirect to local Unbound DNS server who query root DNS servers).

**Comment by user747** [comment]
if using pihole already and want to see or try nextdns blocklist

git clone --depth 1 https://github.com/nextdns/metadata && cd metadata && grep -r '.txt'

**Comment by gwarf** [comment]
Looking at nextdns.io instructions for routers it seems that to avoid manually installing an app that could cause troubles with OpenMPTCPRouter you may have to use their DNS, and linking your VPS IP:
- https://help.nextdns.io/en/articles/3972204-which-setup-type-to-use
- https://help.nextdns.io/en/articles/3941230-what-is-linked-ip

Out of curiosity I've tried to add the DNS they provided me after singing up, but OpenMPTCPRouter doesn't accept it's format:
![Screenshot 2020-07-27 at 10 51 34](https://user-images.githubusercontent.com/451417/88522770-256d1900-cff7-11ea-921a-ee811d56de9a.png)
Wondering about `/use-application-dns.net/`entry I saw https://support.mozilla.org/fr/kb/configurer-reseaux-desactiver-dns-via-https which seems to means that it warns applications like Firefox that DNS over HTTPS won't work. It's meant to enforce using the router's DNS (unbound)?

**Comment by Ysurac** [comment]
@gwarf you use latest stable release ? I don't remember if I solved the issue in current release or after the release.
Yes the ```/use-application-dns.net/``` disable DNS over HTTPS. This force the use of OpenMPTCProuter DNS, it's needed for OMR-ByPass.

**Comment by gwarf** [comment]
Yep sorry I missed to add the version before, it's now it, it should be latest stable.

**Comment by gwarf** [comment]
Is there a way to manually overwrite this conf via SSH and edition of some locale file?

**Comment by Ysurac** [comment]
Via SSH on the router: ```uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'```

**Comment by gwarf** [comment]
So it seems I also need `uci commit dhcp` to save the changes. Can/should I also delete the local/unbound entry to enforce using the new DNS server? Would it affect/break some specific features of OpenMPTCPRouter?

**Comment by Ysurac** [comment]
Yes you have to delete default 127.0.0.1#5353 and this will not break anything in OpenMPTCProuter.

**Comment by rifaterdemsahin** [comment]
so i need to do is 

1. add /use-application-dns.net/
2.XX.XX.XX.XX#53

XX.XX.XX.XX is the nextdns server and 53 is the port.

and it should not kill the router right?

**Comment by gwarf** [comment]
So use-applicaiton-dns.net should already be there, you should see it in the `Network->DHCP & DNS` section.
What I did was:
```sh
# once ssh keys have been configured via the web interface
ssh root@192.168.100.1
# check what is there, to be used to rever if needed
uci get dhcp.@dnsmasq[0].server
# Add the nextdns DNS server, no need to specify the port if it's on 53
uci add_list dhcp.@dnsmasq[0].server='X.X.X.X'
# Save changes
uci commit dhcp
```
Then as I was unsure about the appropriate I went to `Network->DHCP & DNS` to delete the unbound entry `127.0.0.1#5353`, saved and reload then all went fine.

I'm testing nextdns since then, no problem at all. They have a great dashboard, it's also possible to request to get data hosted in the EC and to configure logs retention. And the stats/analytics are quite intereseting, it's what looks the more interesting to me.
Only but gig drawback is that it's all in the hands of an American startup, while I would prefer to be sure that this data will remain private...
So will probably stop in a few days, once I will have a definitive feeling about the service.

A similar dashboard in OpenMPTPCPRouter with something like pihole would be a killer feature
![Screenshot 2020-07-29 at 09 50 49](https://user-images.githubusercontent.com/451417/88772520-2df15b00-d181-11ea-969c-f127deb783ff.png)
![Screenshot 2020-07-29 at 09 49 03](https://user-images.githubusercontent.com/451417/88772526-3053b500-d181-11ea-93cd-77ab6a08ddb9.png)
![Screenshot 2020-07-29 at 09 47 34](https://user-images.githubusercontent.com/451417/88772529-32b60f00-d181-11ea-8513-e61c9ea0793f.png)
![Screenshot 2020-07-29 at 09 47 08](https://user-images.githubusercontent.com/451417/88772551-3c3f7700-d181-11ea-9529-bf25a85c5abd.png)
![Screenshot 2020-07-29 at 09 47 04](https://user-images.githubusercontent.com/451417/88772560-3ea1d100-d181-11ea-80d1-c4d88c1eb5bd.png)





.

**Comment by gwarf** [comment]
Also as here the DNS server is configured on the router it removes the possibility to have per-device stats, it's an aggregation of all the devices from the local network.

**Comment by gwarf** [comment]
I've now moved to Pi-Hole and didn't realised before that nexdns is that close/similar to Pi-hole so OpenMPTCPRouter is really killing everythign else :)
