### ISSUE TITLE
Autoreboot every day.

### ISSUE THREAD

**Issue by dettofatto** [Ysurac/openmptcprouter#1118]
I've set reboot everyday through command in scheduled tasks:
30 4 * * * sleep 70 && touch /etc/banner && reboot
It's correct?
Because I've seen that I can't have correct statistics under
Vnstsat Graphs, because they are resetting at every reboot.

**Comment by Ysurac** [comment]
It's correct.
For vnstats they are by default not saved if omr-quota is not used (to write less data on disk). You can enabled backup on disk in System->OpenMPTCProuter and advanced parameters tab.

**Comment by dooley1981** [comment]
how do I input a specific time? What is the command time on the task above?

**Comment by BigFanOpenmptcprouter** [comment]
> how do I input a specific time? What is the command time on the task above?

The above is placed into the following: /cgi-bin/luci/admin/system/crontab

To input specific time lookup cron documentation or if you want to take shortcut use AI to generate the time for you.

**Comment by BigFanOpenmptcprouter** [comment]
2 question to the OP/developers:
1) why do you do the 70 seconds wait time and then modify the timestamp on /etc/banner ?

Why not go straight to reboot?
ie:
`30 4 * * * reboot`

My gut feeling tells me this is some sort of workaround in place so I would like to know more :)

2) Is there a practical difference on order of the items in the cron? My gut feeling tells me do it in chronological order but I could be completely wrong. On long list of crons it can be difficult to get it right.

Is the time synced via NTP every time before it runs the cron tasks? Otherwise you can easily end up in a boot loop...
