### ISSUE TITLE
[question] Selection of crypto and tunnel protocols 

### ISSUE THREAD

**Issue by Adorfer** [Ysurac/openmptcprouter#1334]
selection of protocolls and crypto: i am **looking for an "algorithm/decision flow chart"**

as far as i understand there is 

- different handling for UDP and TCP payload
- additional VPN for TCP neccesary if a WAN provider filters MPTCP
- different type of crypto or "none"

- what are the Pros and Cons of different methods?
- does "not doing any crypto" help for performance 

- are there recommended settings for _"OMR without AES-NI, weak CPUs"_ in combination with _"multiple +100MBit/s WANs"_?
- what are recommended settings if VPS is showing load and/or latency often, in order to improve?

For reference: Those are the settings im am unsure about. with a fast OMR + fast VPS i do not spot differences (but perhaps i did not try the relevant combinations). 
On the other hand i have an old OpenVPN-only-Setup which seems limited to 70MBit/s in DS, whatever i do (switching methods), despite beeing on a 1000MBit/s WAN (on which a modern OMR gives full power) 

![grafik](https://user-images.githubusercontent.com/10302493/97799056-b1609380-1c2b-11eb-80e8-2676f84f8821.png)

![grafik](https://user-images.githubusercontent.com/10302493/97799081-e53bb900-1c2b-11eb-96c7-90861806c7b8.png)

![grafik](https://user-images.githubusercontent.com/10302493/97799095-0b615900-1c2c-11eb-9709-a936fa5eabb2.png)

**Comment by Ysurac** [comment]
Shadowsocks + Glorytun TCP is the default. Chacha20 is the default on system without AES HW support (else AES is used as default).
For crypto:
* Not doing crypto use less CPU, but it's not recommended (because it's not crypted, but use less CPU).
* Chacha20 is used on CPU without AES support, this use less CPU than AES in this case
* AES is used on CPU with AES support on both side (vps and router), this is fast and don't use much CPU.

For proxy:
* Shadowsocks can be used for TCP only
* V2Ray should work for TCP and UDP. It can do reverse proxy for ports forwarding.
As V2Ray is new in OpenMPTCProuter, I can't say which one is better yet. You need to test.

For VPN:
* Glorytun TCP. It's the default
* Glorytun UDP, it use his own aggregation method based on UDP
* MLVPN, use also his own aggregation method based on UDP
* DSVPN and OpenVPN are TCP based, like glorytun TCP
I can't say which one is the best, you need to test for your use case. VPN is used for anything that is not TCP if shadowsocks is used, and anything that is not TCP or UDP if V2Ray is used, and for all if no proxy is used (it's slower)

MPTCP over VPN use OpenVPN UDP and should be used only if a provider filter MPTCP (and if you are sure it's really the case).

In MPTCP settings, using BLEST scheduler help when there is LTE/wifi connections, using Cubic as TCP congestion control help with bad connections but BBR is better if connections are good.

If VPS is showing a load problem, change VPS.
If the router can't support the speed, use a better architecture/CPU, a RPI(2/3/4) will never work well to aggregate 1Gb/s for example.

**Comment by Malaga82** [comment]
I have few questions if you don't mind.

> For VPN:
> 
> * Glorytun TCP. It's the default

What is its aggregation method?
> * Glorytun UDP, it use his own aggregation method based on UDP

What is "own" mean? 
> * MLVPN, use also his own aggregation method based on UDP
> * DSVPN and OpenVPN are TCP based, like glorytun TCP
>   I can't say which one is the best, you need to test for your use case. VPN is used for anything that is not TCP if shadowsocks is used, and anything that is not TCP or UDP if V2Ray is used, and for all if no proxy is used (it's slower)

So with shadowsocks all VPN's are only for UDP and ICMP, right? It should not do that differences, right?
For V2Ray even lesser, since it's used for TCP an UDP, right?
The only left is with "none" that use VPN for everything, am i right?

I just want to be sure i understood correctly how proxies and VPN's works :)
Thanks

**Comment by Ysurac** [comment]
All VPN based on TCP use MPTCP, so it's the case of glorytun TCP, DSVPN and OpenVPN TCP.
Own method mean that it's VPN that do aggregation without using MPTCP.

With shadowsocks, VPNs are used for anything that is not TCP, so UDP, ICMP, SCTP, RTP,... Same with V2Ray, but V2ray is used for UDP also. And yes with proxy set as none, then only VPN is used. Proxy are faster than VPN in most cases.

**Comment by Malaga82** [comment]
Understood :)
But if i have glorytun UDP ( for testing the bug ) and in MPTCP i have : 
![image](https://user-images.githubusercontent.com/3518802/97803510-45d9ee80-1c4a-11eb-93dd-d8c426b1092c.png)
and 
![image](https://user-images.githubusercontent.com/3518802/97803525-55f1ce00-1c4a-11eb-92e2-76bcf93b50d5.png)
Does it mean that MPTCP is used for proxy part and for UDP ( or other protocols not covered by shadowsocks for example ) the VPN uses its own aggregation that is not necessary MPTCP, right?

**Comment by Ysurac** [comment]
True.

**Comment by Adorfer** [comment]
I now learned that there is a lot of different methods and how they are connected. 
But what are the criteria e.g. 
- when use v2ray instead of shadowsocks
- when use glorytun/mud in UDP mode
- when use glorytun in tcp-mode instead of glorytun udp-mode

a "scenario description"/recommendation list would be nice.
otherwise it's always a bad feedling, not to have tested ALL possible combinations and the fear of missing performance, because beeing lazy.

**Comment by Ysurac** [comment]
There is no criteria, you have to test what is best for you. For v2ray I don't have enough feedback to say anything.
If you don't have issues then you don't have to change settings.

**Comment by Malaga82** [comment]
@Adorfer for what i know, reading the code and least testing, glorytun TCP is an old implementation and compile from: https://github.com/angt/glorytun/releases/tag/v0.0.35 while glorytun UDP is compiled from recent https://github.com/angt/glorytun commits , if read the code well from vps sh script.
What's better, glorytun TCP is old but using TCP is better if connections to/from VPS is not stable, cause of TCP reliability but somehow is slower than UDP cause of handshakes.
glorytun UDP is newer and using UDP is faster but it doesn't have high reliability since it's "connectionless" and there is no error recovery. and use its own data aggregation, mud, that is also newer than mptcp.
I can't say about everything else, i agree that an explanation about all this features would be nice, at least for knowledge.

**Comment by Malaga82** [comment]
the only thing i'm not sure about is this, about glorytun UDP:
![image](https://user-images.githubusercontent.com/3518802/97808763-ff47bc80-1c68-11eb-9f3c-751e5b55d7c6.png)
that is the same as glorytun TCP, maybe since UDP is using MUD, this value is just "dummy".

**Comment by Ysurac** [comment]
I use same interface for Glorytun TCP and UDP, I will make a new interface soon.

**Comment by Malaga82** [comment]
about glorytun i made a simple ping test, between router and server:
UDP mode
10591 packets transmitted, 10507 received, 0.793126% packet loss, time 11143ms
rtt min/avg/max/mdev = 9.317/27.075/713.420/21.100 ms
TCP mode
8102 packets transmitted, 8102 received, 0% packet loss, time 9061ms
rtt min/avg/max/mdev = 10.488/32.197/6565.876/174.823 ms
