### ISSUE TITLE
MPTCP filtered connection as Backup?

### ISSUE THREAD

**Issue by chuotde** [Ysurac/openmptcprouter#2266]
Hi there,

I have a very high latency WAN connection (actually it is a satellite link) and it is a MPTCP filtered link (already verified with MPTCP check tool). Can I set that connection as a Backup? I want OMR to use that connection only when all other connections go down, I don't want to bond that connection.

Please advise.
Thanks

**Comment by Kalimeiro** [comment]
you need to use MPTCP over VPN on this link and set OMRVPN has backup in MPTCP settings (and not the WAN of this link).

**Comment by chuotde** [comment]
Hi Kalimeiro,

Thanks for your input. But my idea is if that link is the only link available, is there any way to bypass the OMR and let traffic go through the link directly to Internet rather than to VPS and to Internet? It may then not add up some latency to users.

Cheers

**Comment by Kalimeiro** [comment]
Hi,

the subject of you'r second message is totally different from you'r first message.

You say you want to use your link has a backup connection, that suppose you have other wan.

And in the second message tell you have only one wan and don't want to use them rather than the VPS and by-pass directly to internet, so : don't set a VPS on you'r OMR and thats good, or switch directly to OpenWRT instead OMR.

Great day.
