### ISSUE TITLE
OpenMPTCP : No data error

### ISSUE THREAD

**Issue by hamzaaboufirass** [Ysurac/openmptcprouter#2639]
I am on openmptcprouter v0.59.1-5.4 r0+16594-ce92de8c8c

everything is configured correctly , 3 wan lines (DHCP) + 1 lan (bridge over two ports) lan has dhcp enabled.

When connecting to VPS i get a No Data error on the status page and no internet is available:
<img width="1287" alt="Screen Shot 2022-11-04 at 19 49 40" src="https://user-images.githubusercontent.com/23054632/200052759-023348da-8e15-49c1-b1e6-d2fd77a06281.png">

<img width="952" alt="Screen Shot 2022-11-04 at 19 50 31" src="https://user-images.githubusercontent.com/23054632/200052887-aa66e00d-800e-42a3-9cf4-230543090149.png">

Is this a bug?

**Comment by Ysurac** [comment]
Please use template when you open an issue.
Try to do a fresh configuration without any bridge.

**Comment by hamzaaboufirass** [comment]
Hello Ysurac,

My apology for the template, didn't pay attention to it.


Tried without bridge still same issue.

I have uploaded the log as well.


[log-mptcp.zip](https://github.com/Ysurac/openmptcprouter/files/9941514/log-mptcp.zip)

**Comment by Network-Traditions** [comment]
I had this issue when I modified the default LAN configuration of OMR (see #2540).  After I identified the problem with changing LAN naming, I rebuilt OMR without modifying the default LAN (eth0) setup and the "No data" issue was resolved.  Due to my limited experience and knowledge of OMR/OpenWRT configuration, I'm guessing changing the LAN name requires additional modification of firewall rules and/or other impacted settings.  Not wanting to waste time identifying those issues, I opted for a clean build with the default LAN setup.
