### ISSUE TITLE
Add Shadowsocks eBPF support

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#285]
Add this: https://github.com/SPYFF/shadowsocks-libev-nocrypto/tree/ebpf
Work only without encryption.

A test with that enabled : https://blog.freifunk.net/2018/08/14/gsoc-2018-kernel-space-socks-proxy-for-linux-final/

For now packages for OpenWrt are done, need to enable that in VPS script, add support in interface and test this.

**Comment by Ysurac** [comment]
Test version of VPS script have eBPF enabled too.
Next release will have support in interface via a "none-ebpf" encryption method because encryption is not supported with eBPF shadowsocks patch.

**Comment by PxxBxx** [comment]
@Ysurac it seems promising (many don't need encryption as packets are dispatched through many wans), but aren't you afraid of the author note : 
` [...] there is an issue with the current version [...] because in the current kernel implementation sometimes if an error happens during the transmission, the packet size returned instead of the error code [...] `
Do you know if this is fixed ?

**Comment by Ysurac** [comment]
No idea. But for now it's not yet working in OpenMPTCProuter at all.

**Comment by SPYFF** [comment]
Hello! Thanks for interest. I notified John Fastabend from the bug, he is the author of the current sockmap implementation (the original impelemtation which was an kernel patch RFC, but never merged, did by Tom Herbert. I think that is not merged because its instrumented the ioctl interface but the eBPF interface is more general and more elegant). John told me he will add an option for the sockmap code, to allow 1:1 mapping between sockets, in that way he can solve the issue of the silently dropped packets. The current implementation still drops packets, when the target socket of the redirection go out of memory. 
I try to "decipher" the kernel code myself to solve the issue, but its pretty demanding without good kernel programming skills. Also, here is the issue opened by John: https://github.com/cilium/cilium/issues/6438

Also the socket buffer recycling would be an additional optimization, because we can reuse the already allocated memory chunk of the received packet for sending. For MPTCP I'm not quite sure it can work but for one path maybe possible: still great benefit.

**Comment by Ysurac** [comment]
For now I can't make it work, maybe it's because MPTCP... I have no more time to test for now. So I will wait for better patches :)
