### ISSUE TITLE
OMR 0.60 BETA SNAPSHOT - OpenVPN Enhancement

### ISSUE THREAD

**Issue by KaleiRo** [Ysurac/openmptcprouter#3100]
**Is your enhancement proposal related to a problem? Please describe.**

1°) in OMR Wizard, we dont have choice to choose OpenVPN TCP or OpenVPN UDP, we have only OpenVPN and it used TCP by default.
2°) we need to remove "reneg-sec 0" "sndbuf 0" and "rcvbuf 0" because zero values ​​are useless for now and it's the server which must push the configuration to the client.
3°) add disable-dco ONLY for OpenVPN TCP not for OpenVPN UDP.
4°) fix data-ciphers to the same as server : data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
5°) add tls-v2-crypt (need to make creation of key on VPS parts)

**Comment by xzjq** [comment]
FYI, using OpenVPN UDP will come at a substantial performance penalty given that UDP does not aggregate well in OMR. Basically, UDP traffic does not aggregate at all.

The primary reason for using the VPN in the default setup (i.e. as configured via OMR Settings Wizard) is to allow tunneled transport, via TCP, of traffic *other* than TCP so that non-TCP traffic can take advantage of MPTCP.

If you configure OMR to use UDP for its VPN then your non-TCP traffic will use *only* the master WAN. If that is the desired use case you would be better off bypassing the OMR relay to VPS for that traffic.
