### ISSUE TITLE
Unable to view Network Overview

### ISSUE THREAD

**Issue by ccmks** [Ysurac/openmptcprouter#3241]
Unfortunately, I can't view the information to fill in the template

Whenever, I try to load the status page, I keep getting this

![image](https://github.com/Ysurac/openmptcprouter/assets/49300986/d774d782-9e65-4a15-ad2c-0e39e0b16eff)

**Comment by Ysurac** [comment]
Please use the template in anycase...
And update.

**Comment by ccmks** [comment]
Like I said, I can't retrieve anything from status page in order to fill in the template, because in status page, it contains all the information needed to fill in the template.

What do I need to do in order to diagnose this issue?

Thank you

**Comment by Ysurac** [comment]
Version of the router is at the bottom of each web interface, for the VPS it's in /etc/motd. And no need help of status page for device platform, VPS provider, expected behavior, context,...
This really help to go faster and not loosing too much times by asking not needed log/info/...
Did you have previously the status ? it's a new install or not ? did you change anything ? Did you check system log ? something is working or nothing at all ?

**Comment by ceruleanBlazar** [comment]
I used to have the same issue on previous versions.
This solved the issue for me:
https://github.com/Ysurac/openmptcprouter/issues/2195#issuecomment-1170484474

**Comment by ccmks** [comment]
> I used to have the same issue on previous versions. This solved the issue for me: [#2195 (comment)](https://github.com/Ysurac/openmptcprouter/issues/2195#issuecomment-1170484474)

Unfortunately, this didn't help

Thank you

**Comment by vempire-ghost** [comment]
In beta1, there was a bug for a certain period that caused this issue. Try updating to RC2, which should have it fixed.
