### ISSUE TITLE
more than one default VPN is enabled 

### ISSUE THREAD

**Issue by ElinaKir** [Ysurac/openmptcprouter#3452]
how to solve this problem? 
![2024-07-17_13-39-45](https://github.com/user-attachments/assets/387ee0c2-797f-4687-aa38-55d2fcc7d6f5)

**Comment by mrkaffeine92** [comment]
Click VPN from the ribbon and take a look at the various instances. Depending on what you're running when you go to System ->OpenMPTCPRouter, you should only have that configuration active/enabled.

For example, in OpenMPTCPRouter leaf, I click [under Advanced Settings a few lines down] to tick the box "Show advanced settings".
-I then see under VPN settings, my default VPN is OpenVPN TCP out of the various selections.

I go back to VPN card and click on the OpenVPN instance. The only enabled/started name should be "omr" (tcp-client) for this config.
If you were to run OpenVPN Bonding, then you'd have another two boxes enabled instead of the omr. Similar if you were running MLVPN - OpenVPN card would be disabled and you'd have the instance enabled there.

My guess is either you activated the wrong protocols in addition to what the script booted or it didn't properly release and end when you were playing around with it.

If you still have trouble, post some pics of the aforementioned pages and we'll get you some help.
