### ISSUE TITLE
gateway down, multipath current state is off

### ISSUE THREAD

**Issue by wackal** [Ysurac/openmptcprouter#603]
## Actual Behavior
![image](https://user-images.githubusercontent.com/54185128/63207029-dec13000-c0bf-11e9-8937-1d8daa1a9555.png)

## Steps to Reproduce the Problem

  1.wan1 (master) adsl
  2.wan2 (on) 4g router (work if i connect directly on it)
  3.this config its ok for 3 month and tomorow i have this message "gateway down, multipath current state is off"

## Specifications

  - OpenMPTCProuter version: 0.51.5
  - OpenMPTCProuter VPS version: 0.999
  - OpenMPTCProuter platform: RPI3

**Comment by Ysurac** [comment]
It's because gateway of wan2 doesn't answer to ping and omr-tracker can't ping any IP using this interface. So this interface doesn't answer at all for the router.
You can check "System log" to have more info.

You should check cables. You can also try via SSH on the router to ping the gateway "192.168.1.254"

**Comment by wackal** [comment]
ping not good on SSH
i check cables and reinstall openmptcprouter on my RPI3 and all is ok now
thanks Ysurac
