### ISSUE TITLE
Use Glorytun VPN for UDP instead of shadowsocks

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/openmptcprouter#64]
There is some problems with shadowsocks UDP.
Disable UDP shadowsocks by default.
Maybe detect use shadowsocks UDP only when Glorytun VPN is down.

**Comment by Ysurac** [comment]
Since release 0.20, UDP doesn't use shadowsocks by default.
Need to make a script to use it if glorytun is down (at user choice).

**Comment by Ysurac** [comment]
This will be available in next release.

**Comment by Bumpalert** [comment]
@Ysurac When I need port forwarding & UDP video uploading, which VPN i should use. Disabling Glorytun TCP, i am lossing port forwarding. As shadowsocks UDP not working, if I enable Glorytun UDP & Glorytun TCP together which will be choosen by live streaming video content?

**Comment by Ysurac** [comment]
Port forwarding work with all VPNs available in wizard page. You can't enable multiples VPN at the same time.

**Comment by Bumpalert** [comment]
@ysurac I noticed that If I change to vray & glorytun udp from shadow socks & glorytun tcp, the port forwarding will stop working and vpn wont connect on 0.58RC2. I tried 2-3 times to make sure that this is the problem and undoing the change and setting tcp vpn and port forwarding will start working.

![image](https://user-images.githubusercontent.com/56679716/120535389-8a0bb800-c400-11eb-8843-93560d98ddf0.png)
![WhatsApp Image 2021-06-03 at 12 06 06 AM](https://user-images.githubusercontent.com/56679716/120535850-174f0c80-c401-11eb-914a-caf55f6b914c.jpeg)


 I didn't upgrade after 0.58rc2 as server script update from 1025 may need to reset vps,as running 1024 to 1025 didnt upgrade without reseting the vps. Is there any  easy way to uninstall existing vps script and install updated one.

**Comment by Ysurac** [comment]
You must upgrade to 0.1025 on VPS side if you want 0.58 to work.

**Comment by Bumpalert** [comment]
> 
> 
> You must upgrade to 0.1025 on VPS side if you want 0.58 to work.

I am actually on 0.1025. I didn't upgrade after that because I don't wanted to reset vps frequently(if any new vps script 0.1025+ is released with 0.58rc5) as 0.58rc2 works stable for me. 0.58rc2 port forwarding is working on tcp vpn and shadow socks. But as you suggested earlier, when I moved to glorytun UDP & VRAY on wizard, port forwarding stopped working & vpn disconnected(I did the setting change actually on the omr forwarded port on vps through internet ) . If I put back to tcp glorytun(using local network as no port forwarding active) port forwarding will work as earlier.
